import axios from 'axios'

export default () => ({
  books: [
    // {
    //   id: '14356',
    //   author: 'Vetulani, Jerzy (1936-2017).',
    //   title: 'Ćwiczenia duszy, rozciąganie mózgu',
    //   publisher: 'Społeczny Instytut Wydawniczy ',
    //   city: 'Kraków',
    //   year: '2016',
    //   category: 'religie'
    // }
  ],
  counter: 111,
  websitedata: null,
  slider: null,
  sugestions: [
    'Adam Mickiewicz',
    'Adam Asnyk',
    'Juliusz Słowacki',
    'Andrzej Sapkowski',
    'Edward Nowak'
  ],
  list: [
    {
      id: '14356',
      author: 'Vetulani, Jerzy (1936-2017).',
      title: 'Ćwiczenia duszy, rozciąganie mózgu',
      publisher: 'Społeczny Instytut Wydawniczy ',
      city: 'Kraków',
      year: '2016',
      category: 'religie'
    },
    {
      id: '14366',
      author: 'Lunde, Maja (1975- ).',
      title: 'Historia pszczół',
      publisher: 'Wydawnictwo Literackie',
      city: 'Kraków',
      year: '2017',
      category: 'beletrystyka'
    },
    {
      id: '14367',
      author: 'Gumundur Andri Thorsson (1957- ).',
      title: 'Miasteczko w Islandii',
      publisher: 'Wielka Litera',
      city: 'Warszawa',
      year: 'copyright ',
      category: 'beletrystyka'
    }
  ],
  // nuxtServerInit({ dispatch }) {
  //   console.warn(1)
  //   dispatch('LOAD_WEBSITEDATA')
  //   return Promise.resolve(dispatch('core/load'))
  // },
  // actions: {
  //   nuxtServerInit({ commit }, { req }) {
  //     if ($store.state.list === []) {
  //       console.log('list')
  //       console.log(list)
  //       list = { count: '3' }
  //     }
  //     // if (req.session.user) {
  //     //   commit('user', req.session.user)
  //     // }
  //   }
  // },

  categories: [
    'lektury',
    'beletrystyka',
    'dydaktyka i pedagogi',
    'tarnoviana',
    'poezja',
    'powieść młodzieżowa',
    'religie',
    'podróże',
    'fantastyka',
    'słowniki językowe',
    'nauka i wiedza ogóln',
    'historia Polski',
    'powieść historyczna',
    'socjologia',
    'sensacja',
    'historia II wojny',
    'polityka',
    'etnografia',
    'elektronika',
    'obróbka skrawaniem',
    'ekonomia',
    'biografie',
    'botanika',
    'sport',
    'bibliotekarstwo',
    'psychologia',
    'kryminał',
    'utwory humorystyczne',
    'krajoznawstwo',
    'astronomia',
    'wojsko',
    'zoologia',
    'pamiętniki osobiste',
    'przemysł chemiczny',
    'publicystyka',
    'fotografia',
    'języki programowania',
    'malarstwo',
    'ekologia',
    'historia literatury',
    'powieść wojenna',
    'prawo',
    'inżynieria wodna',
    'inżynieria sanitarna',
    'antropologia ',
    'medycyna',
    'filozofia',
    'miscellanea',
    'dramat',
    'historia powszechna',
    'opisy krajów',
    'fizyka',
    'programy komputerowe',
    'sztuka',
    'horror',
    'histora II wojny',
    'film',
    'moda',
    'nauki przyrodn. ogól',
    'językoznawstwo',
    'rolnictwo, leśnictwo',
    'badania materiałów',
    'biologia',
    'aforyzmy',
    'architektura',
    'eseje',
    'informatyka',
    'geografia'
  ]

  // categories: [
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'dydaktyka i pedagogi',
  //   'tarnoviana',
  //   'poezja',
  //   'powieść młodzieżowa',
  //   'religie',
  //   'beletrystyka',
  //   'podróże',
  //   'fantastyka',
  //   'beletrystyka',
  //   'słowniki językowe',
  //   'słowniki językowe',
  //   'lektury',
  //   'poezja',
  //   'nauka i wiedza ogóln',
  //   'lektury',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'historia Polski',
  //   'tarnoviana',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'powieść historyczna',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'socjologia',
  //   'fantastyka',
  //   'beletrystyka',
  //   'powieść historyczna',
  //   'beletrystyka',
  //   'religie',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'historia II wojny',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'polityka',
  //   'etnografia',
  //   'socjologia',
  //   'etnografia',
  //   'sensacja',
  //   'socjologia',
  //   'elektronika',
  //   'obróbka skrawaniem',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'sensacja',
  //   'powieść historyczna',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'fantastyka',
  //   'ekonomia',
  //   'beletrystyka',
  //   'biografie',
  //   'sensacja',
  //   'sensacja',
  //   'religie',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'botanika',
  //   'religie',
  //   'sensacja',
  //   'tarnoviana',
  //   'poezja',
  //   'lektury',
  //   'lektury',
  //   'beletrystyka',
  //   'lektury',
  //   'sport',
  //   'religie',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'bibliotekarstwo',
  //   'psychologia',
  //   'beletrystyka',
  //   'psychologia',
  //   'kryminał',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'utwory humorystyczne',
  //   'krajoznawstwo',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'historia Polski',
  //   'tarnoviana',
  //   'poezja',
  //   'lektury',
  //   'astronomia',
  //   'słowniki językowe',
  //   'słowniki językowe',
  //   'wojsko',
  //   'poezja',
  //   'zoologia',
  //   'słowniki językowe',
  //   'beletrystyka',
  //   'poezja',
  //   'biografie',
  //   'beletrystyka',
  //   'kryminał',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'przemysł chemiczny',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'kryminał',
  //   'publicystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'krajoznawstwo',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'powieść historyczna',
  //   'powieść historyczna',
  //   'fotografia',
  //   'fotografia',
  //   'fotografia',
  //   'języki programowania',
  //   'malarstwo',
  //   'malarstwo',
  //   'malarstwo',
  //   'malarstwo',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'kryminał',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'kryminał',
  //   'powieść młodzieżowa',
  //   'religie',
  //   'fantastyka',
  //   'fantastyka',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'publicystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść historyczna',
  //   'zoologia',
  //   'publicystyka',
  //   'bibliotekarstwo',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'biografie',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'publicystyka',
  //   'publicystyka',
  //   'biografie',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'ekologia',
  //   'historia literatury',
  //   'sensacja',
  //   'beletrystyka',
  //   'malarstwo',
  //   'powieść wojenna',
  //   'publicystyka',
  //   'kryminał',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść wojenna',
  //   'prawo',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'inżynieria wodna',
  //   'kryminał',
  //   'kryminał',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść historyczna',
  //   'poezja',
  //   'lektury',
  //   'beletrystyka',
  //   'powieść historyczna',
  //   'powieść historyczna',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'publicystyka',
  //   'biografie',
  //   'inżynieria sanitarna',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'pamiętniki osobiste',
  //   'utwory humorystyczne',
  //   'beletrystyka',
  //   'poezja',
  //   'beletrystyka',
  //   'fantastyka',
  //   'zoologia',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'psychologia',
  //   'ekologia',
  //   'polityka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'historia II wojny',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'antropologia ',
  //   'beletrystyka',
  //   'medycyna',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'psychologia',
  //   'beletrystyka',
  //   'etnografia',
  //   'fantastyka',
  //   'poezja',
  //   'beletrystyka',
  //   'poezja',
  //   'sensacja',
  //   'filozofia',
  //   'religie',
  //   'beletrystyka',
  //   'miscellanea',
  //   'fantastyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'religie',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'poezja',
  //   'powieść młodzieżowa',
  //   'publicystyka',
  //   'beletrystyka',
  //   'dramat',
  //   'medycyna',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'historia powszechna',
  //   'socjologia',
  //   'fantastyka',
  //   'fantastyka',
  //   'polityka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'poezja',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'fantastyka',
  //   'psychologia',
  //   'poezja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'opisy krajów',
  //   'beletrystyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'poezja',
  //   'beletrystyka',
  //   'biografie',
  //   'publicystyka',
  //   'fantastyka',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'poezja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'poezja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'fantastyka',
  //   'historia Polski',
  //   'poezja',
  //   'zoologia',
  //   'poezja',
  //   'dydaktyka i pedagogi',
  //   'podróże',
  //   'poezja',
  //   'powieść młodzieżowa',
  //   'historia powszechna',
  //   'poezja',
  //   'poezja',
  //   'powieść historyczna',
  //   'beletrystyka',
  //   'powieść historyczna',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fizyka',
  //   'dramat',
  //   'beletrystyka',
  //   'programy komputerowe',
  //   'opisy krajów',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'historia powszechna',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'opisy krajów',
  //   'historia Polski',
  //   'historia Polski',
  //   'botanika',
  //   'beletrystyka',
  //   'programy komputerowe',
  //   'sztuka',
  //   'fantastyka',
  //   'fantastyka',
  //   'historia Polski',
  //   'programy komputerowe',
  //   'fantastyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'sensacja',
  //   'horror',
  //   'powieść młodzieżowa',
  //   'histora II wojny',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'poezja',
  //   'beletrystyka',
  //   'biografie',
  //   'sensacja',
  //   'publicystyka',
  //   'fantastyka',
  //   'medycyna',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'psychologia',
  //   'fantastyka',
  //   'prawo',
  //   'powieść historyczna',
  //   'psychologia',
  //   'beletrystyka',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'sensacja',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'sensacja',
  //   'sensacja',
  //   'fantastyka',
  //   'sensacja',
  //   'fantastyka',
  //   'filozofia',
  //   'fantastyka',
  //   'film',
  //   'beletrystyka',
  //   'biografie',
  //   'powieść młodzieżowa',
  //   'poezja',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'socjologia',
  //   'beletrystyka',
  //   'kryminał',
  //   'moda',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'nauki przyrodn. ogól',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'moda',
  //   'historia II wojny',
  //   'historia II wojny',
  //   'psychologia',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'fantastyka',
  //   'językoznawstwo',
  //   'kryminał',
  //   'sensacja',
  //   'pamiętniki osobiste',
  //   'powieść historyczna',
  //   'religie',
  //   'beletrystyka',
  //   'kryminał',
  //   'sensacja',
  //   'beletrystyka',
  //   'podróże',
  //   'sport',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'kryminał',
  //   'beletrystyka',
  //   'rolnictwo, leśnictwo',
  //   'moda',
  //   'sensacja',
  //   'fantastyka',
  //   'fantastyka',
  //   'socjologia',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'kryminał',
  //   'kryminał',
  //   'sensacja',
  //   'kryminał',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'sensacja',
  //   'religie',
  //   'badania materiałów',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'powieść młodzieżowa',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'lektury',
  //   'podróże',
  //   'beletrystyka',
  //   'sensacja',
  //   'fantastyka',
  //   'biografie',
  //   'beletrystyka',
  //   'utwory humorystyczne',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'biologia',
  //   'psychologia',
  //   'opisy krajów',
  //   'opisy krajów',
  //   'historia powszechna',
  //   'beletrystyka',
  //   'astronomia',
  //   'fantastyka',
  //   'poezja',
  //   'sensacja',
  //   'psychologia',
  //   'kryminał',
  //   'psychologia',
  //   'sensacja',
  //   'sensacja',
  //   'etnografia',
  //   'powieść historyczna',
  //   'powieść historyczna',
  //   'powieść historyczna',
  //   'fantastyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'podróże',
  //   'aforyzmy',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'powieść historyczna',
  //   'etnografia',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'powieść wojenna',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść wojenna',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'publicystyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'sport',
  //   'beletrystyka',
  //   'kryminał',
  //   'beletrystyka',
  //   'biografie',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'kryminał',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'podróże',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'religie',
  //   'religie',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'kryminał',
  //   'medycyna',
  //   'beletrystyka',
  //   'zoologia',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'publicystyka',
  //   'biografie',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'podróże',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'fantastyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'fantastyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'biografie',
  //   'botanika',
  //   'beletrystyka',
  //   'polityka',
  //   'beletrystyka',
  //   'biografie',
  //   'religie',
  //   'astronomia',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'architektura',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'biografie',
  //   'moda',
  //   'moda',
  //   'astronomia',
  //   'sensacja',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'fantastyka',
  //   'powieść historyczna',
  //   'biografie',
  //   'biografie',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'biografie',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'psychologia',
  //   'historia powszechna',
  //   'tarnoviana',
  //   'dydaktyka i pedagogi',
  //   'tarnoviana',
  //   'historia literatury',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'kryminał',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'beletrystyka',
  //   'biografie',
  //   'historia literatury',
  //   'historia literatury',
  //   'historia literatury',
  //   'socjologia',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'historia powszechna',
  //   'publicystyka',
  //   'sensacja',
  //   'publicystyka',
  //   'publicystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'lektury',
  //   'lektury',
  //   'poezja',
  //   'sensacja',
  //   'sensacja',
  //   'fantastyka',
  //   'zoologia',
  //   'nauka i wiedza ogóln',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'powieść młodzieżowa',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'poezja',
  //   'poezja',
  //   'poezja',
  //   'dydaktyka i pedagogi',
  //   'powieść młodzieżowa',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'sensacja',
  //   'biografie',
  //   'biografie',
  //   'film',
  //   'biografie',
  //   'biografie',
  //   'malarstwo',
  //   'sztuka',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'socjologia',
  //   'socjologia',
  //   'pamiętniki osobiste',
  //   'socjologia',
  //   'ekonomia',
  //   'psychologia',
  //   'filozofia',
  //   'psychologia',
  //   'psychologia',
  //   'psychologia',
  //   'psychologia',
  //   'eseje',
  //   'informatyka',
  //   'publicystyka',
  //   'pamiętniki osobiste',
  //   'socjologia',
  //   'pamiętniki osobiste',
  //   'publicystyka',
  //   'socjologia',
  //   'socjologia',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'beletrystyka',
  //   'pamiętniki osobiste',
  //   'sensacja',
  //   'beletrystyka',
  //   'sensacja',
  //   'fantastyka',
  //   'historia powszechna',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'fantastyka',
  //   'zoologia',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'powieść młodzieżowa',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'historia Polski',
  //   'sensacja',
  //   'botanika',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'publicystyka',
  //   'beletrystyka',
  //   'biografie',
  //   'socjologia',
  //   'historia literatury',
  //   'historia literatury',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'geografia',
  //   'sensacja',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'podróże',
  //   'tarnoviana',
  //   'tarnoviana',
  //   'beletrystyka',
  //   'beletrystyka',
  //   'tarnoviana',
  //   'fotografia',
  //   'tarnoviana',
  //   'tarnoviana'
  // ]
})

// export const actions = {
// async nuxtServerInit({ dispatch }) {
//   console.warn(1)
//   dispatch('LOAD_WEBSITEDATA')
//   // return await dispatch('LOAD_SLIDER')
// },
// async LOAD_WEBSITEDATA({ commit }) {
//   // const data = await axios.get('api/v1/sugestions.json')
//   const data = axios.get('api/v1/sugestions.json')
//   // .then((res) => {
//   // console.warn(res.data)
//   // state.sugestions = res.data
//   // })
//   // .catch((error) => {
//   // console.warn(error)
//   // })
//   console.warn(2)
//   commit('SET_WEBSITEDATA', data)
// },

//   async LOAD_SLIDER({ commit }) {
//     const data = await axios.get('api/v1/02.20.min.json')
//     commit('SET_SLIDER', data.data)
//     console.warn('commit SLIDER')
//   }
// }
// export const mutations = {
//   SET_WEBSITEDATA(state, data) {
//     state.websitedata = data
//   },
//   SET_SLIDER(state, slider) {
//     state.slider = slider
//   }
// }
